export const types = {
    REQUEST_ACTIVATE_CELL: 'REQUEST_ACTIVATE_CELL',
    REQUEST_CREATE_PATTERN: 'REQUEST_CREATE_PATTERN',
    REQUEST_INITIAL_CELLS: 'REQUEST_INITIAL_CELLS',    
    RECEIVE_INITIAL_CELLS: 'RECEIVE_INITIAL_CELLS',
    RECEIVE_ACTIVATE_CELL: 'RECEIVE_ACTIVATE_CELL',
    RECEIVE_UPDATE_CELLS: 'RECEIVE_UPDATE_CELLS',
    RECEIVE_CREATE_PATTERN: 'RECEIVE_CREATE_PATTERN',
};